paths:
  raw_json_dir: "./data/03-jsonified"
  dataset_csv: "./data/04-ready_4_training/classifier_dataset.csv"
  evaluation_dir: "./evaluation"

data:
  input: "./data/04-ready_4_training/classifier_dataset.csv"
  target: "label"
  text_column: "text"

model:
  type: "bertimbau"
  pretrained_model: "neuralmind/bert-base-portuguese-cased"
  save_path: "./models/zmb_model"

training:
  test_size: 0.2
  random_state: 42
  epochs: 3
  batch_size: 4
